/*******************************************************************************
* File Name: main.c
*
* Version: 1.0
*
* Description:
*  This example demonstrates how to setup an IPv6 communication infrastructure 
*  between two devices over a BLE transport using L2CAP channel. Creation 
*  and transmission of IPv6 packets over BLE is not part of this example.
*
*  Router sends generated packets with different content to Node in the loop 
*  and validate them with the afterwards received data packet. Node simply wraps
*  received data coming from Node, back to the Router.
*
* Note:
*
* Hardware Dependency:
*  CY8CKIT-042 BLE
*
********************************************************************************
* Copyright 2016, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "main.h"
#include <stdbool.h>

uint16 connIntv = CYBLE_GAPP_CONNECTION_INTERVAL_MIN;   /* in milliseconds / 1.25ms */
bool l2capConnected = false;
bool l2capReadReceived = false;

uint8 ipv6LoopbackBuffer[L2CAP_MAX_LEN];
uint16 ipv6LoopbackLength = L2CAP_MAX_LEN; 


/* L2CAP Channel ID and parameters for the peer device */
CYBLE_L2CAP_CBFC_CONN_IND_PARAM_T l2capParameters;


/*******************************************************************************
* Function Name: AppCallBack()
********************************************************************************
*
* Summary:
*   This is an event callback function to receive events from the BLE Component.
*
* Parameters:
*  event - the event code
*  *eventParam - the event parameters
*
* Theory:
* The function is responsible for handling the events generated by the stack.
* It first starts advertising once the stack is initialized. 
* Upon advertising timeout this function enters Hibernate mode.
* 
*******************************************************************************/
void AppCallBack(uint32 event, void* eventParam)
{
    CYBLE_API_RESULT_T apiResult;
    CYBLE_GAP_BD_ADDR_T localAddr;
    uint8 i;
    
    switch (event)
	{
        /**********************************************************
        *                       General Events
        ***********************************************************/
		case CYBLE_EVT_STACK_ON: /* This event received when component is Started */
            /* Register IPSP protocol multiplexer to L2CAP and 
            *  set the initial Receive Credit Low Mark for Based Flow Control mode 
            */
            apiResult = CyBle_L2capCbfcRegisterPsm(CYBLE_L2CAP_PSM_LE_PSM_IPSP, LE_WATER_MARK_IPSP);
            if(apiResult != CYBLE_ERROR_OK)
            {
                DBG_PRINTF("CyBle_L2capCbfcRegisterPsm API Error: %d \r\n", apiResult);
            }

            /* Enter into discoverable mode so that remote can search it. */
            apiResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            if(apiResult != CYBLE_ERROR_OK)
            {
                DBG_PRINTF("StartAdvertisement API Error: %d \r\n", apiResult);
            }
            DBG_PRINTF("Bluetooth On, StartAdvertisement with addr: ");
            localAddr.type = 0u;
            CyBle_GetDeviceAddress(&localAddr);
            for(i = CYBLE_GAP_BD_ADDR_SIZE; i > 0u; i--)
            {
                DBG_PRINTF("%2.2x", localAddr.bdAddr[i-1]);
            }
            DBG_PRINTF("\r\n");
            break;
		case CYBLE_EVT_TIMEOUT: 
            DBG_PRINTF("CYBLE_EVT_TIMEOUT: %x \r\n", *(CYBLE_TO_REASON_CODE_T *)eventParam);
			break;
		case CYBLE_EVT_HARDWARE_ERROR:    /* This event indicates that some internal HW error has occurred. */
            DBG_PRINTF("Hardware Error: %x \r\n", *(uint8 *)eventParam);
			break;
        case CYBLE_EVT_HCI_STATUS:
            DBG_PRINTF("CYBLE_EVT_HCI_STATUS: %x \r\n", *(uint8 *)eventParam);
			break;
    	case CYBLE_EVT_STACK_BUSY_STATUS:
        #if(DEBUG_UART_FULL)
            DBG_PRINTF("CYBLE_EVT_STACK_BUSY_STATUS: %x\r\n", CyBle_GattGetBusyStatus());
        #endif /* DEBUG_UART_FULL */
            break;
            
        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        case CYBLE_EVT_GAP_AUTH_REQ:
            DBG_PRINTF("CYBLE_EVT_AUTH_REQ: security=%x, bonding=%x, ekeySize=%x, err=%x \r\n", 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).security, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).bonding, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).ekeySize, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).authErr);
            break;
        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
            DBG_PRINTF("CYBLE_EVT_PASSKEY_ENTRY_REQUEST press 'p' to enter passkey \r\n");
            break;
        case CYBLE_EVT_GAP_PASSKEY_DISPLAY_REQUEST:
            DBG_PRINTF("CYBLE_EVT_PASSKEY_DISPLAY_REQUEST %6.6ld \r\n", *(uint32 *)eventParam);
            break;
        case CYBLE_EVT_GAP_KEYINFO_EXCHNGE_CMPLT:
            DBG_PRINTF("CYBLE_EVT_GAP_KEYINFO_EXCHNGE_CMPLT \r\n");
            break;
        case CYBLE_EVT_GAP_AUTH_COMPLETE:
            DBG_PRINTF("AUTH_COMPLETE: security:%x, bonding:%x, ekeySize:%x, authErr %x \r\n", 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).security, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).bonding, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).ekeySize, 
                (*(CYBLE_GAP_AUTH_INFO_T *)eventParam).authErr);
            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:
            DBG_PRINTF("CYBLE_EVT_AUTH_FAILED: %x \r\n", *(uint8 *)eventParam);
            break;
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            DBG_PRINTF("CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP, state: %x\r\n", CyBle_GetState());
            if(CYBLE_STATE_DISCONNECTED == CyBle_GetState())
            {   
                /* Fast and slow advertising period complete, go to low power  
                 * mode (Hibernate mode) and wait for an external
                 * user event to wake up the device again */
                DBG_PRINTF("Hibernate \r\n");
                UpdateLedState();
            #if (DEBUG_UART_ENABLED == ENABLED)
                while((UART_DEB_SpiUartGetTxBufferSize() + UART_DEB_GET_TX_FIFO_SR_VALID) != 0);
            #endif /* (DEBUG_UART_ENABLED == ENABLED) */
                SW2_ClearInterrupt();
                Wakeup_Interrupt_ClearPending();
                Wakeup_Interrupt_Start();
                CySysPmHibernate();
            }
            break;
        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
            UpdateLedState();
            connIntv = ((CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T *)eventParam)->connIntv * 5u /4u;
            DBG_PRINTF("CYBLE_EVT_GAP_DEVICE_CONNECTED: connIntv = %d ms \r\n", connIntv);
            break;
        case CYBLE_EVT_GAPC_CONNECTION_UPDATE_COMPLETE:
            connIntv = ((CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T *)eventParam)->connIntv * 5u /4u;
            DBG_PRINTF("CYBLE_EVT_CONNECTION_UPDATE_COMPLETE: connIntv = %d ms \r\n", connIntv);
            break;
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            DBG_PRINTF("CYBLE_EVT_GAP_DEVICE_DISCONNECTED: %x\r\n", *(uint8 *)eventParam);
            apiResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            if(apiResult != CYBLE_ERROR_OK)
            {
                DBG_PRINTF("StartAdvertisement API Error: %d \r\n", apiResult);
            }
            break;
        case CYBLE_EVT_GAP_ENCRYPT_CHANGE:
            DBG_PRINTF("CYBLE_EVT_GAP_ENCRYPT_CHANGE: %x \r\n", *(uint8 *)eventParam);
            break;
        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            /* Triggered on server side when client sends read request and when
            * characteristic has CYBLE_GATT_DB_ATTR_CHAR_VAL_RD_EVENT property set.
            * This event could be ignored by application unless it need to response
            * by error response which needs to be set in gattErrorCode field of
            * event parameter. */
            DBG_PRINTF("CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ: handle: %x \r\n", 
                ((CYBLE_GATTS_CHAR_VAL_READ_REQ_T *)eventParam)->attrHandle);
            break;

        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:
            DBG_PRINTF("CYBLE_EVT_GATT_CONNECT_IND: %x, %x \r\n", cyBle_connHandle.attId, cyBle_connHandle.bdHandle);
            break;
        case CYBLE_EVT_GATT_DISCONNECT_IND:
            DBG_PRINTF("CYBLE_EVT_GATT_DISCONNECT_IND \r\n");
            break;

        /**********************************************************
        *                       L2CAP Events
        ***********************************************************/
        case CYBLE_EVT_L2CAP_CBFC_CONN_IND:
            l2capParameters = *((CYBLE_L2CAP_CBFC_CONN_IND_PARAM_T *)eventParam);
            DBG_PRINTF("CYBLE_EVT_L2CAP_CBFC_CONN_IND: bdHandle=%d, lCid=%d, psm=%d,connParam mtu=%d, mps=%d, credit=%d ", 
                l2capParameters.bdHandle,
                l2capParameters.lCid,
                l2capParameters.psm,
                l2capParameters.connParam.mtu,
                l2capParameters.connParam.mps,
                l2capParameters.connParam.credit);
            if(l2capParameters.psm == CYBLE_L2CAP_PSM_LE_PSM_IPSP)
            {
                CYBLE_L2CAP_CBFC_CONNECT_PARAM_T connParam;
                connParam.mtu    = CYBLE_L2CAP_MTU;
                connParam.mps    = CYBLE_L2CAP_MPS;
                connParam.credit = LE_DATA_CREDITS_IPSP;
                apiResult = CyBle_L2capCbfcConnectRsp(l2capParameters.lCid,
                                CYBLE_L2CAP_CONNECTION_SUCCESSFUL, &connParam);
                DBG_PRINTF("SUCCESSFUL \r\n"); 
                l2capConnected = true;
            }
            else
            {
                apiResult = CyBle_L2capCbfcConnectRsp(l2capParameters.lCid,
                                CYBLE_L2CAP_CONNECTION_REFUSED_PSM_UNSUPPORTED, &l2capParameters.connParam);
                DBG_PRINTF("UNSUPPORTED \r\n"); 
            }
            if(apiResult != CYBLE_ERROR_OK)
            {
                DBG_PRINTF("CyBle_L2capCbfcConnectRsp API Error: %d \r\n", apiResult);
            }
            break;

        case CYBLE_EVT_L2CAP_CBFC_DISCONN_IND:
            DBG_PRINTF("CYBLE_EVT_L2CAP_CBFC_DISCONN_IND: lCid=%d \r\n", *(uint16 *)eventParam);
            l2capConnected = false;
            break;

        /* Following two events are required to receive data */        
        case CYBLE_EVT_L2CAP_CBFC_DATA_READ:
            {
                CYBLE_L2CAP_CBFC_RX_PARAM_T *rxDataParam = (CYBLE_L2CAP_CBFC_RX_PARAM_T *)eventParam;
                DBG_PRINTF("<- EVT_L2CAP_CBFC_DATA_READ: lCid=%d, result=%d, len=%d", 
                    rxDataParam->lCid,
                    rxDataParam->result,
                    rxDataParam->rxDataLength);
            #if(DEBUG_UART_FULL)  
                DBG_PRINTF(", data:");
                for(i = 0; i < rxDataParam->rxDataLength; i++)
                {
                    DBG_PRINTF("%2.2x", rxDataParam->rxData[i]);
                }
            #endif /* DEBUG_UART_FULL */
                DBG_PRINTF("\r\n");
                /* Data is received from Router. Copy the data to a memory buffer */
                if(rxDataParam->rxDataLength <= L2CAP_MAX_LEN)
                {
                    ipv6LoopbackLength = rxDataParam->rxDataLength;
                }
                else
                {
                    ipv6LoopbackLength = L2CAP_MAX_LEN;
                }
                memcpy(ipv6LoopbackBuffer, rxDataParam->rxData, ipv6LoopbackLength);
                l2capReadReceived = true;
            }
            break;

        case CYBLE_EVT_L2CAP_CBFC_RX_CREDIT_IND:
            {
                CYBLE_L2CAP_CBFC_LOW_RX_CREDIT_PARAM_T *rxCreditParam = (CYBLE_L2CAP_CBFC_LOW_RX_CREDIT_PARAM_T *)eventParam;
                DBG_PRINTF("CYBLE_EVT_L2CAP_CBFC_RX_CREDIT_IND: lCid=%d, credit=%d \r\n", 
                    rxCreditParam->lCid,
                    rxCreditParam->credit);

                /* This event informs that receive credits reached the low mark. 
                 * If the device expects more data to receive, send more credits back to the peer device.
                 */
                apiResult = CyBle_L2capCbfcSendFlowControlCredit(rxCreditParam->lCid, LE_DATA_CREDITS_IPSP);
                if(apiResult != CYBLE_ERROR_OK)
                {
                    DBG_PRINTF("CyBle_L2capCbfcSendFlowControlCredit API Error: %d \r\n", apiResult);
                }
            }
            break;

        /* Following events are required to send data */
        case CYBLE_EVT_L2CAP_CBFC_TX_CREDIT_IND:
            DBG_PRINTF("CYBLE_EVT_L2CAP_CBFC_TX_CREDIT_IND: lCid=%d, result=%d, credit=%d \r\n", 
                ((CYBLE_L2CAP_CBFC_LOW_TX_CREDIT_PARAM_T *)eventParam)->lCid,
                ((CYBLE_L2CAP_CBFC_LOW_TX_CREDIT_PARAM_T *)eventParam)->result,
                ((CYBLE_L2CAP_CBFC_LOW_TX_CREDIT_PARAM_T *)eventParam)->credit);
            break;
        
        case CYBLE_EVT_L2CAP_CBFC_DATA_WRITE_IND:
            #if(DEBUG_UART_FULL)
            {
                CYBLE_L2CAP_CBFC_DATA_WRITE_PARAM_T *writeDataParam = (CYBLE_L2CAP_CBFC_DATA_WRITE_PARAM_T*)eventParam;
                DBG_PRINTF("CYBLE_EVT_L2CAP_CBFC_DATA_WRITE_IND: lCid=%d, result=%d \r\n", 
                    writeDataParam->lCid,
                    writeDataParam->result);
            }
            #endif /* DEBUG_UART_FULL */
            break;

        /**********************************************************
        *                       Other Events
        ***********************************************************/
        case CYBLE_EVT_PENDING_FLASH_WRITE:
            /* Inform application that flash write is pending. Stack internal data 
            * structures are modified and require to be stored in Flash using 
            * CyBle_StoreBondingData() */
            DBG_PRINTF("CYBLE_EVT_PENDING_FLASH_WRITE\r\n");
            break;
        default:
            DBG_PRINTF("OTHER event: %lx \r\n", event);
			break;
	}

}


/*******************************************************************************
* Function Name: Timer_Interrupt
********************************************************************************
*
* Summary:
*  Handles the Interrupt Service Routine for the WDT timer.
*
*******************************************************************************/
CY_ISR(Timer_Interrupt)
{
    static uint8 led = LED_OFF;

    /* Blink green LED to indicate that device advertises */
    if(CyBle_GetState() == CYBLE_STATE_ADVERTISING)
    {
        led ^= LED_OFF;
        Advertising_LED_Write(led);
    }
}


/*******************************************************************************
* Function Name: UpdateLedState
********************************************************************************
*
* Summary:
*  This function updates led status based on current BLE state.
*
* Parameters:
*  None
*
* Return:
*  None
*
*******************************************************************************/
void UpdateLedState(void)
{
   
    if(CyBle_GetState() == CYBLE_STATE_INITIALIZING)
    {   
        Advertising_LED_Write(LED_OFF);
        Disconnect_LED_Write(LED_OFF);
        Simulation_LED_Write(LED_OFF);
    }
    else if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
    {   
        Advertising_LED_Write(LED_OFF);
        Disconnect_LED_Write(LED_ON);
        Simulation_LED_Write(LED_OFF);
    }
    else if(CyBle_GetState() == CYBLE_STATE_CONNECTED)
    {
        Advertising_LED_Write(LED_OFF);
        Disconnect_LED_Write(LED_OFF);
        if(l2capReadReceived == true)
        {
            Simulation_LED_Write(LED_ON);
        }
        else
        {
            Simulation_LED_Write(LED_OFF);
        }
    }
    else
    {
        /* Advertising led is handled in Timer_Interrupt */
    }
}


/*******************************************************************************
* Function Name: LowPowerImplementation()
********************************************************************************
* Summary:
*  Implements low power in the project.
*
* Parameters:
*  None
*
* Return:
*  None
*
* Theory:
*  The function tries to enter deep sleep as much as possible - whenever the 
*  BLE is idle and the UART transmission/reception is not happening. 
*  At all other times, the function tries to enter CPU sleep.
*
*******************************************************************************/
static void LowPowerImplementation(void)
{
    CYBLE_LP_MODE_T bleMode;
    uint8 interruptStatus;
    
    /* For advertising and connected states, implement deep sleep 
     * functionality to achieve low power in the system. For more details
     * on the low power implementation, refer to the Low Power Application 
     * Note.
     */
    if((CyBle_GetState() == CYBLE_STATE_ADVERTISING) || 
       (CyBle_GetState() == CYBLE_STATE_CONNECTED))
    {
        /* Request BLE subsystem to enter into Deep-Sleep mode between connection and advertising intervals */
        bleMode = CyBle_EnterLPM(CYBLE_BLESS_DEEPSLEEP);
        /* Disable global interrupts */
        interruptStatus = CyEnterCriticalSection();
        /* When BLE subsystem has been put into Deep-Sleep mode */
        if(bleMode == CYBLE_BLESS_DEEPSLEEP)
        {
            /* And it is still there or ECO is on */
            if((CyBle_GetBleSsState() == CYBLE_BLESS_STATE_ECO_ON) || 
               (CyBle_GetBleSsState() == CYBLE_BLESS_STATE_DEEPSLEEP))
            {
            #if (DEBUG_UART_ENABLED == ENABLED)
                /* Put the CPU into the Deep-Sleep mode when all debug information has been sent */
                if((UART_DEB_SpiUartGetTxBufferSize() + UART_DEB_GET_TX_FIFO_SR_VALID) == 0u)
                {
                    CySysPmDeepSleep();
                }
                else /* Put the CPU into Sleep mode and let SCB to continue sending debug data */
                {
                    CySysPmSleep();
                }
            #else
                CySysPmDeepSleep();
            #endif /* (DEBUG_UART_ENABLED == ENABLED) */
            }
        }
        else /* When BLE subsystem has been put into Sleep mode or is active */
        {
            /* And hardware doesn't finish Tx/Rx operation - put the CPU into Sleep mode */
            if(CyBle_GetBleSsState() != CYBLE_BLESS_STATE_EVENT_CLOSE)
            {
                CySysPmSleep();
            }
        }
        /* Enable global interrupt */
        CyExitCriticalSection(interruptStatus);
    }
}


/*******************************************************************************
* Function Name: main()
********************************************************************************
* 
* Summary:
*  Main function for the project.
*
* Parameters:
*  None
*
* Return:
*  None
*
* Theory:
*  The function starts BLE and UART components.
*  This function processes all BLE events and also implements the low power 
*  functionality.
*
*******************************************************************************/
int main()
{
    CYBLE_API_RESULT_T apiResult;
    CYBLE_STACK_LIB_VERSION_T stackVersion;
    
    CyGlobalIntEnable;  
    
#if (DEBUG_UART_ENABLED == ENABLED)
	UART_DEB_Start();
#endif /* (DEBUG_UART_ENABLED == ENABLED) */
    DBG_PRINTF("BLE Node Example Project \r\n");
    
    /* Start CYBLE component and register generic event handler */
    apiResult = CyBle_Start(AppCallBack);
    UpdateLedState();
    if(apiResult != CYBLE_ERROR_OK)
    {
        DBG_PRINTF("CyBle_Start API Error: %d \r\n", apiResult);
    }
    
    apiResult = CyBle_GetStackLibraryVersion(&stackVersion);
    if(apiResult != CYBLE_ERROR_OK)
    {
        DBG_PRINTF("CyBle_GetStackLibraryVersion API Error: 0x%2.2x \r\n", apiResult);
    }
    else
    {
        DBG_PRINTF("Stack Version: %d.%d.%d.%d \r\n", stackVersion.majorVersion, 
            stackVersion.minorVersion, stackVersion.patch, stackVersion.buildNumber);
    }
    
    /* Register Timer_Interrupt() by the WDT COUNTER2 to generate interrupt every second */
    CySysWdtSetInterruptCallback(CY_SYS_WDT_COUNTER2, Timer_Interrupt);
    /* Enable the COUNTER2 ISR handler. */
    CySysWdtEnableCounterIsr(CY_SYS_WDT_COUNTER2);

    for(;;)
    {              
        /* Process all the generated events. */
        CyBle_ProcessEvents();

        /* To achieve low power in the device */
        LowPowerImplementation();

        if((CyBle_GetState() == CYBLE_STATE_CONNECTED) && (l2capConnected == true))
        {
            /* Keep sending the data to the router, until TX credits are over */
            if((cyBle_busyStatus == 0u) && (l2capReadReceived == true))
            {
                UpdateLedState();
                l2capReadReceived = false;
                apiResult = CyBle_L2capChannelDataWrite(l2capParameters.bdHandle,
                                l2capParameters.lCid, ipv6LoopbackBuffer, ipv6LoopbackLength);
                DBG_PRINTF("-> CyBle_L2capChannelDataWrite API result: %d \r\n", apiResult);
                UpdateLedState();
            }
        }
        
        /* Store bonding data to flash only when all debug information has been sent */
    #if (DEBUG_UART_ENABLED == ENABLED)
        if((cyBle_pendingFlashWrite != 0u) &&
           ((UART_DEB_SpiUartGetTxBufferSize() + UART_DEB_GET_TX_FIFO_SR_VALID) == 0u))
    #else
        if(cyBle_pendingFlashWrite != 0u)
    #endif /* (DEBUG_UART_ENABLED == ENABLED) */
        {
            apiResult = CyBle_StoreBondingData(0u);
            DBG_PRINTF("Store bonding data, status: %x \r\n", apiResult);
        }
    }
}  


/* [] END OF FILE */
